### ISSUE TITLE
 Flutter Engine Artifact Download Fails (maybe with incorrect file name?)

### ISSUE THREAD

**Issue by JesperBellenbaum** [meta-flutter/workspace_automation#25]
Hi @jwinarske,

I'm encountering an issue with the Flutter engine artifact download in the workspace automation script. This seems to be a continuation of the problem described in issue #24, but with some new details.

**Current Behavior:**
When running the `flutter_workspace.py` script, the engine artifact download fails with the following error:

```
...
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.24.0, on Ubuntu 24.04 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    ! Flutter version 3.24.0 on channel [user-branch] at /home/<user>/Documents/dev/workspace-automation/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Linux toolchain - develop for Linux desktop
[✓] VS Code (version 1.92.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
Engine Version: b8800d88be4866db1b15f8b954ab2573bba9960f
Working Directory: /home/<user>/Documents/dev/workspace-automation/.config/flutter_workspace/flutter-engine
*********************************
** Downloading Engine artifact **
*********************************
** Downloading linux-x64-embedder.zip via https://storage.googleapis.com/flutter_infra_release/flutter/b8800d88be4866db1b15f8b954ab2573bba9960f/linux-x64/linux-x64-embedder
************************
** Download Status: 0 **
************************
***********************************************
** Failed to download linux-x64-embedder.zip **
***********************************************
...
```

**Expected Behavior:**
The script should successfully download the Flutter engine artifact and continue with the setup process.

**Possible Cause:**
The URL being used to download the artifact may be incorrect. It appears that the `.zip` extension is missing from the URL.

**Steps to Reproduce:**
1. Clone the workspace-automation repository
2. Run the `flutter_workspace.py` script
3. Observe the error message about failing to download the engine artifact

**Environment:**
- OS: Ubuntu 24.04 LTS
- Python version: 3.12
- Flutter version: 3.24.0

Thank you for your help in addressing this issue and for making the world of embedded Flutter more accessible!

**Comment by jwinarske** [comment]
@JesperBllnbm I see the issue.  Should have a fix in today

**Comment by jwinarske** [comment]
@JesperBllnbm Looks like they no longer package libflutter_engine.so.  So this will have to wait for the [flutter-engine](https://github.com/meta-flutter/flutter-engine) repo to come online.  They also dropped arm64.  It's not clear who the customer is for this new format.

**Comment by JesperBellenbaum** [comment]
Hi @jwinarske,

I was able to move forward by manually downloading the flutter engine from here: https://github.com/sony/flutter-embedded-linux/releases/tag/b8800d88be

**Comment by jwinarske** [comment]
@JesperBllnbm v2.0 branch has been updated to pull engine artifacts from https://github.com/meta-flutter/flutter-engine/
