### ISSUE TITLE
Missing QEMU image file in AGL configuration

### ISSUE THREAD

**Issue by JesperBellenbaum** [meta-flutter/workspace_automation#26]
Hi @jwinarske 

The current configuration file for the AGL QEMU (master and octopus) environment references a file that no longer exists. 

- **Missing file:** `qemux86-64/agl-ivi-demo-platform-flutter-qemux86-64.wic.vmdk.xz`
- **Referenced in:** 
  ```json
  "artifacts": {
    "http": {
      "url": "https://download.automotivelinux.org/AGL/release/${RELEASE_NAME}/${RELEASE_VERSION}",
      "artifacts": {
        "x86_64": [
          {
            "endpoint": "/qemux86-64/deploy/images/qemux86-64/agl-ivi-demo-platform-flutter-qemux86-64.wic.vmdk.xz"
          }
        ],
        // ...
      }
    }
  }
  ```

Is it possible that the file `agl-ivi-demo-flutter-qemux86-64.wic.vmdk.xz` is the intended replacement for the missing file? 

https://download.automotivelinux.org/AGL/snapshots/ricefish/latest/qemux86-64/deploy/images/qemux86-64/

Thanks again!

**Comment by jwinarske** [comment]
Please use downstream configs found in meta-agl-flutter as I indicated in other issue.  These configs here are for reference only; they were created here, with no intent to maintain.

flutter_workspace.py (implementation) is independent of the data (configs).

**Comment by jwinarske** [comment]
This config will be merged to meta-flutter-agl end of week:
https://github.com/meta-flutter/workspace-automation/blob/jw/ricefish_18.0.0/configs/agl-qemu-ricefish-18.0.0.json
