### ISSUE TITLE
Minimum working example on macOS and Ubuntu

### ISSUE THREAD

**Issue by timcreatedit** [meta-flutter/workspace_automation#27]
Hey @jwinarske! Thanks so much for your amazing efforts.

I'm really struggling to get this script to work at all on macOS M2 (and Ubuntu for that matter).
There seem to be issues with recognising cocoapods, which are also visible in the [action failures](https://github.com/meta-flutter/workspace-automation/actions/runs/10463046951/job/28974402547).

On Ubuntu, many more issues (see #26, and #25) are popping up. I'm wondering if you guys are using this script still, because we're really having a lot of trouble to get anything working.

If there is a configuration that is known to work, we'd be really grateful if you could help us out by sharing what we might be doing wrong.

Thanks again!

**Comment by jwinarske** [comment]
macOS M2 is no longer supported, as I have not been tracking macOS changes, and no one was actively using it.  Support for macOS will be available via the upcoming `emb_cli` dart tool.

Also all AGL/target configs are for reference only; with the exception of desktop-homescreen and associated stack.  The expectation is that configs are unique to a given organization that have specific device requirements.

**Comment by jwinarske** [comment]
Also feel free to discuss further on the Embedded Flutter Discord channel.
